### ISSUE TITLE
xray-webhook程序内存占用很高

### ISSUE THREAD

**Issue by leveryd** [leveryd-asm/asm#4]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/1846319/210362293-16ac29a2-ce1b-47f7-8554-3705e0315f9e.png">

是否正常？

**Comment by leveryd** [comment]
不太对劲的样子
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/1846319/210363534-96f663eb-a955-48b3-9c44-f8b87407bc70.png">
<img width="836" alt="image" src="https://user-images.githubusercontent.com/1846319/210363579-cb1e2cca-fca3-4263-a0d9-4935c47948db.png">

**Comment by Evilran** [comment]
https://github.com/leveryd-asm/tools/blob/e00eb1101ba398852d37c8b5a07bcdf2aecd08a6/xray-webhook/main.go#L86

是否需要 req.Body.Close()？
